insert into produto (descricao, preco_unitario) values ('Cookie Dough - Double', 186.52);
insert into produto (descricao, preco_unitario) values ('Salmon - Canned', 224.31);
insert into produto (descricao, preco_unitario) values ('Grenadillo', 437.83);
insert into produto (descricao, preco_unitario) values ('Pepper - Red Bell', 759.56);
insert into produto (descricao, preco_unitario) values ('Mix - Cappucino Cocktail', 55.47);
insert into produto (descricao, preco_unitario) values ('Nacho Chips', 384.51);
insert into produto (descricao, preco_unitario) values ('Island Oasis - Pina Colada', 736.65);
insert into produto (descricao, preco_unitario) values ('Pan Grease', 138.62);
insert into produto (descricao, preco_unitario) values ('Energy - Boo - Koo', 16.5);
insert into produto (descricao, preco_unitario) values ('Bread - Kimel Stick Poly', 741.78);
insert into produto (descricao, preco_unitario) values ('Water - Green Tea Refresher', 941.33);
insert into produto (descricao, preco_unitario) values ('Chicken Thigh - Bone Out', 362.28);
insert into produto (descricao, preco_unitario) values ('Sour Puss Raspberry', 958.73);
insert into produto (descricao, preco_unitario) values ('Pepper - Paprika, Hungarian', 790.83);
insert into produto (descricao, preco_unitario) values ('Anisette - Mcguiness', 376.5);
insert into produto (descricao, preco_unitario) values ('Wine - Chardonnay South', 200.06);
insert into produto (descricao, preco_unitario) values ('Watercress', 775.14);
insert into produto (descricao, preco_unitario) values ('Wine - Delicato Merlot', 567.17);
insert into produto (descricao, preco_unitario) values ('Napkin - Beverge, White 2 - Ply', 630.79);
insert into produto (descricao, preco_unitario) values ('Madeira', 609.57);
insert into produto (descricao, preco_unitario) values ('Calypso - Pineapple Passion', 267.23);
insert into produto (descricao, preco_unitario) values ('Sauce - Alfredo', 397.73);
insert into produto (descricao, preco_unitario) values ('Wild Boar - Tenderloin', 501.34);
insert into produto (descricao, preco_unitario) values ('Yogurt - Banana, 175 Gr', 331.47);
insert into produto (descricao, preco_unitario) values ('Icecream Bar - Del Monte', 19.9);
insert into produto (descricao, preco_unitario) values ('Napkin - Dinner, White', 475.05);
insert into produto (descricao, preco_unitario) values ('Celery Root', 924.42);
insert into produto (descricao, preco_unitario) values ('Tomatoes - Roma', 195.35);
insert into produto (descricao, preco_unitario) values ('Slt - Individual Portions', 368.68);
insert into produto (descricao, preco_unitario) values ('Milk - Homo', 961.92);
insert into produto (descricao, preco_unitario) values ('Pork - Inside', 662.28);
insert into produto (descricao, preco_unitario) values ('Galliano', 486.34);
insert into produto (descricao, preco_unitario) values ('Potatoes - Yukon Gold 5 Oz', 259.62);
insert into produto (descricao, preco_unitario) values ('Croissant, Raw - Mini', 505.08);
insert into produto (descricao, preco_unitario) values ('Cod - Fillets', 335.81);
insert into produto (descricao, preco_unitario) values ('Cheese - St. Andre', 248.1);
insert into produto (descricao, preco_unitario) values ('Wine - Cotes Du Rhone Parallele', 347.3);
insert into produto (descricao, preco_unitario) values ('Tea - Herbal - 6 Asst', 529.97);
insert into produto (descricao, preco_unitario) values ('Pie Filling - Apple', 111.96);
insert into produto (descricao, preco_unitario) values ('Cheese - Fontina', 940.35);
insert into produto (descricao, preco_unitario) values ('Truffle Shells - Semi - Sweet', 885.68);
insert into produto (descricao, preco_unitario) values ('Garbage Bags - Black', 945.82);
insert into produto (descricao, preco_unitario) values ('Table Cloth 53x69 White', 614.18);
insert into produto (descricao, preco_unitario) values ('Wine - Magnotta - Bel Paese White', 558.38);
insert into produto (descricao, preco_unitario) values ('Red Snapper - Fillet, Skin On', 174.11);
insert into produto (descricao, preco_unitario) values ('Jam - Apricot', 295.09);
insert into produto (descricao, preco_unitario) values ('Cheese Cloth No 100', 478.91);
insert into produto (descricao, preco_unitario) values ('Oil - Food, Lacquer Spray', 394.64);
insert into produto (descricao, preco_unitario) values ('Soup Campbells Turkey Veg.', 40.52);
insert into produto (descricao, preco_unitario) values ('Chivas Regal - 12 Year Old', 150.28);
insert into produto (descricao, preco_unitario) values ('Neckerchief Blck', 128.58);
insert into produto (descricao, preco_unitario) values ('Wine - Sauvignon Blanc', 840.89);
insert into produto (descricao, preco_unitario) values ('Juice - Apple 284ml', 242.06);
insert into produto (descricao, preco_unitario) values ('Silicone Paper 16.5x24', 879.66);
insert into produto (descricao, preco_unitario) values ('Glass - Juice Clear 5oz 55005', 272.66);
insert into produto (descricao, preco_unitario) values ('Soup - Cream Of Broccoli', 432.4);
insert into produto (descricao, preco_unitario) values ('Crackers - Water', 724.91);
insert into produto (descricao, preco_unitario) values ('Chips - Potato Jalapeno', 125.77);
insert into produto (descricao, preco_unitario) values ('Brandy Apricot', 84.18);
insert into produto (descricao, preco_unitario) values ('Beans - Kidney, Canned', 724.61);
insert into produto (descricao, preco_unitario) values ('Lettuce - California Mix', 359.9);
insert into produto (descricao, preco_unitario) values ('Plate - Foam, Bread And Butter', 792.97);
insert into produto (descricao, preco_unitario) values ('Crab - Dungeness, Whole, live', 888.44);
insert into produto (descricao, preco_unitario) values ('Sherbet - Raspberry', 515.01);
insert into produto (descricao, preco_unitario) values ('Nut - Hazelnut, Ground, Natural', 637.16);
insert into produto (descricao, preco_unitario) values ('Wine - Chateauneuf Du Pape', 551.64);
insert into produto (descricao, preco_unitario) values ('Tart Shells - Sweet, 4', 949.22);
insert into produto (descricao, preco_unitario) values ('Onions - Red', 441.16);
insert into produto (descricao, preco_unitario) values ('Bread - Frozen Basket Variety', 968.33);
insert into produto (descricao, preco_unitario) values ('Pineapple - Golden', 331.87);
insert into produto (descricao, preco_unitario) values ('Ecolab - Balanced Fusion', 193.56);
insert into produto (descricao, preco_unitario) values ('Tomatoes - Heirloom', 55.95);
insert into produto (descricao, preco_unitario) values ('Veal - Tenderloin, Untrimmed', 304.32);
insert into produto (descricao, preco_unitario) values ('Nut - Walnut, Pieces', 858.78);
insert into produto (descricao, preco_unitario) values ('Savory', 972.04);
insert into produto (descricao, preco_unitario) values ('Wine - Alsace Riesling Reserve', 161.58);
insert into produto (descricao, preco_unitario) values ('Pails With Lids', 730.61);
insert into produto (descricao, preco_unitario) values ('Coffee - Dark Roast', 486.46);
insert into produto (descricao, preco_unitario) values ('Chocolate Bar - Coffee Crisp', 355.11);
insert into produto (descricao, preco_unitario) values ('Mussels - Frozen', 579.66);
insert into produto (descricao, preco_unitario) values ('Chinese Foods - Plain Fried Rice', 287.02);
insert into produto (descricao, preco_unitario) values ('Muffin Mix - Oatmeal', 232.94);
insert into produto (descricao, preco_unitario) values ('Jam - Raspberry,jar', 259.89);
insert into produto (descricao, preco_unitario) values ('Cup - 8oz Coffee Perforated', 291.53);
insert into produto (descricao, preco_unitario) values ('Flavouring - Orange', 345.62);
insert into produto (descricao, preco_unitario) values ('Banana - Leaves', 52.57);
insert into produto (descricao, preco_unitario) values ('Celery', 479.77);
insert into produto (descricao, preco_unitario) values ('Coffee - Decaffeinato Coffee', 377.16);
insert into produto (descricao, preco_unitario) values ('Wine - Casablanca Valley', 271.85);
insert into produto (descricao, preco_unitario) values ('Sauerkraut', 952.3);
insert into produto (descricao, preco_unitario) values ('Squid U5 - Thailand', 453.21);
insert into produto (descricao, preco_unitario) values ('Tahini Paste', 997.56);
insert into produto (descricao, preco_unitario) values ('Chicken - Ground', 133.06);
insert into produto (descricao, preco_unitario) values ('Guinea Fowl', 665.32);
insert into produto (descricao, preco_unitario) values ('Wine - Red, Pelee Island Merlot', 794.48);
insert into produto (descricao, preco_unitario) values ('Pears - Bosc', 558.39);
insert into produto (descricao, preco_unitario) values ('Steel Wool S.o.s', 783.58);
insert into produto (descricao, preco_unitario) values ('Seedlings - Clamshell', 445.02);
insert into produto (descricao, preco_unitario) values ('Steamers White', 823.59);
insert into produto (descricao, preco_unitario) values ('Lid - Translucent, 3.5 And 6 Oz', 730.4);
insert into produto (descricao, preco_unitario) values ('Monkfish - Fresh', 853.81);
insert into produto (descricao, preco_unitario) values ('Table Cloth 54x72 Colour', 691.11);
insert into produto (descricao, preco_unitario) values ('Nacho Chips', 872.86);
insert into produto (descricao, preco_unitario) values ('Onion Powder', 874.21);
insert into produto (descricao, preco_unitario) values ('Mushroom - Trumpet, Dry', 569.96);
insert into produto (descricao, preco_unitario) values ('Tomato - Green', 737.4);
insert into produto (descricao, preco_unitario) values ('Peas - Pigeon, Dry', 628.33);
insert into produto (descricao, preco_unitario) values ('Pepper - Pablano', 606.25);
insert into produto (descricao, preco_unitario) values ('Soup V8 Roasted Red Pepper', 947.55);
insert into produto (descricao, preco_unitario) values ('Sauce - Marinara', 224.64);
insert into produto (descricao, preco_unitario) values ('Cheese - Brie,danish', 637.36);
insert into produto (descricao, preco_unitario) values ('Pea - Snow', 408.76);
insert into produto (descricao, preco_unitario) values ('Basil - Primerba, Paste', 348.26);
insert into produto (descricao, preco_unitario) values ('Grenadillo', 648.59);
insert into produto (descricao, preco_unitario) values ('Foil Wrap', 636.33);
insert into produto (descricao, preco_unitario) values ('Yeast Dry - Fleischman', 701.64);
insert into produto (descricao, preco_unitario) values ('Puree - Guava', 697.49);
insert into produto (descricao, preco_unitario) values ('Bread - Ciabatta Buns', 261.42);
insert into produto (descricao, preco_unitario) values ('Pork - Ham, Virginia', 705.26);
insert into produto (descricao, preco_unitario) values ('Tart Shells - Sweet, 4', 559.88);
insert into produto (descricao, preco_unitario) values ('Bulgar', 540.87);
insert into produto (descricao, preco_unitario) values ('Mushroom - Trumpet, Dry', 670.65);
insert into produto (descricao, preco_unitario) values ('Chives - Fresh', 400.45);
insert into produto (descricao, preco_unitario) values ('Tarragon - Primerba, Paste', 422.01);
insert into produto (descricao, preco_unitario) values ('Trout - Smoked', 391.44);
insert into produto (descricao, preco_unitario) values ('Pastry - Plain Baked Croissant', 59.3);
insert into produto (descricao, preco_unitario) values ('Ice Cream - Strawberry', 593.11);
insert into produto (descricao, preco_unitario) values ('Cookies Almond Hazelnut', 45.65);
insert into produto (descricao, preco_unitario) values ('Daikon Radish', 958.31);
insert into produto (descricao, preco_unitario) values ('Onions - Red', 24.44);
insert into produto (descricao, preco_unitario) values ('Scrubbie - Scotchbrite Hand Pad', 92.54);
insert into produto (descricao, preco_unitario) values ('Basil - Thai', 646.89);
insert into produto (descricao, preco_unitario) values ('Table Cloth 53x69 White', 388.41);
insert into produto (descricao, preco_unitario) values ('Pineapple - Golden', 138.23);
insert into produto (descricao, preco_unitario) values ('Spice - Onion Powder Granulated', 66.36);
insert into produto (descricao, preco_unitario) values ('Scallops - U - 10', 163.59);
insert into produto (descricao, preco_unitario) values ('Cocoa Powder - Dutched', 58.04);
insert into produto (descricao, preco_unitario) values ('Sweet Pea Sprouts', 569.49);
insert into produto (descricao, preco_unitario) values ('Sprouts - Onion', 383.4);
insert into produto (descricao, preco_unitario) values ('Latex Rubber Gloves Size 9', 430.0);
insert into produto (descricao, preco_unitario) values ('Wine - Zonnebloem Pinotage', 620.92);
insert into produto (descricao, preco_unitario) values ('Pastry - Cherry Danish - Mini', 957.37);
insert into produto (descricao, preco_unitario) values ('Squid - Tubes / Tenticles 10/20', 887.36);
insert into produto (descricao, preco_unitario) values ('Straw - Regular', 653.55);
insert into produto (descricao, preco_unitario) values ('Scallops - U - 10', 897.87);
insert into produto (descricao, preco_unitario) values ('Chocolate - Milk', 219.44);
insert into produto (descricao, preco_unitario) values ('Pepper - Julienne, Frozen', 266.92);
insert into produto (descricao, preco_unitario) values ('Wine - Balbach Riverside', 703.73);
insert into produto (descricao, preco_unitario) values ('Pepper - Red Thai', 459.34);
insert into produto (descricao, preco_unitario) values ('Tea - Lemon Green Tea', 57.54);
insert into produto (descricao, preco_unitario) values ('Bread - Flat Bread', 106.91);
insert into produto (descricao, preco_unitario) values ('Chocolate - Milk, Callets', 447.97);
insert into produto (descricao, preco_unitario) values ('Sprouts - China Rose', 361.99);
insert into produto (descricao, preco_unitario) values ('Lettuce - Green Leaf', 619.56);
insert into produto (descricao, preco_unitario) values ('Carroway Seed', 860.37);
insert into produto (descricao, preco_unitario) values ('Cheese - Valancey', 328.13);
insert into produto (descricao, preco_unitario) values ('Cheese - Pont Couvert', 393.0);
insert into produto (descricao, preco_unitario) values ('Boogies', 975.27);
insert into produto (descricao, preco_unitario) values ('Soy Protein', 56.43);
insert into produto (descricao, preco_unitario) values ('Cheese - Mozzarella, Shredded', 583.55);
insert into produto (descricao, preco_unitario) values ('Gatorade - Lemon Lime', 339.68);
insert into produto (descricao, preco_unitario) values ('Bread - Italian Corn Meal Poly', 257.15);
insert into produto (descricao, preco_unitario) values ('Sauce - Alfredo', 63.51);
insert into produto (descricao, preco_unitario) values ('Ocean Spray - Ruby Red', 462.59);
insert into produto (descricao, preco_unitario) values ('Soup - Knorr, Veg / Beef', 962.04);
insert into produto (descricao, preco_unitario) values ('Beef - Baby, Liver', 745.07);
insert into produto (descricao, preco_unitario) values ('Juice Peach Nectar', 915.76);
insert into produto (descricao, preco_unitario) values ('Beef - Chuck, Boneless', 314.01);
insert into produto (descricao, preco_unitario) values ('Browning Caramel Glace', 54.88);
insert into produto (descricao, preco_unitario) values ('Sauce - Thousand Island', 316.55);
insert into produto (descricao, preco_unitario) values ('Soup - Canadian Pea, Dry Mix', 851.05);
insert into produto (descricao, preco_unitario) values ('Vodka - Hot, Lnferno', 109.21);
insert into produto (descricao, preco_unitario) values ('Coffee - Colombian, Portioned', 645.67);
insert into produto (descricao, preco_unitario) values ('Ostrich - Prime Cut', 793.72);
insert into produto (descricao, preco_unitario) values ('Wine - Niagara Peninsula Vqa', 134.41);
insert into produto (descricao, preco_unitario) values ('Soup - Campbells - Chicken Noodle', 711.33);
insert into produto (descricao, preco_unitario) values ('Cheese - St. Andre', 224.81);
insert into produto (descricao, preco_unitario) values ('Energy - Boo - Koo', 163.99);
insert into produto (descricao, preco_unitario) values ('Beef Cheek Fresh', 909.72);
insert into produto (descricao, preco_unitario) values ('Plate - Foam, Bread And Butter', 527.39);
insert into produto (descricao, preco_unitario) values ('Beef - Kindney, Whole', 806.49);
insert into produto (descricao, preco_unitario) values ('Beer - Steamwhistle', 445.96);
insert into produto (descricao, preco_unitario) values ('Stock - Beef, Brown', 428.72);
insert into produto (descricao, preco_unitario) values ('Wine - Rosso Del Veronese Igt', 376.62);
insert into produto (descricao, preco_unitario) values ('Wine - Cava Aria Estate Brut', 538.59);
insert into produto (descricao, preco_unitario) values ('Apples - Spartan', 699.93);
insert into produto (descricao, preco_unitario) values ('Tarragon - Fresh', 815.92);
insert into produto (descricao, preco_unitario) values ('Island Oasis - Raspberry', 543.3);
insert into produto (descricao, preco_unitario) values ('Veal - Round, Eye Of', 491.02);
insert into produto (descricao, preco_unitario) values ('Milk - Chocolate 250 Ml', 894.82);
insert into produto (descricao, preco_unitario) values ('Tomatoes - Cherry', 402.96);
insert into produto (descricao, preco_unitario) values ('Bread - Bagels, Mini', 483.44);
insert into produto (descricao, preco_unitario) values ('Triple Sec - Mcguinness', 510.51);
insert into produto (descricao, preco_unitario) values ('Muffin Mix - Lemon Cranberry', 249.57);
insert into produto (descricao, preco_unitario) values ('Coffee - Irish Cream', 425.84);
insert into produto (descricao, preco_unitario) values ('Cabbage - Nappa', 156.08);
insert into produto (descricao, preco_unitario) values ('Dish Towel', 435.16);
insert into produto (descricao, preco_unitario) values ('Jam - Raspberry', 320.16);
insert into produto (descricao, preco_unitario) values ('Longos - Chicken Wings', 278.19);
insert into produto (descricao, preco_unitario) values ('Potatoes - Purple, Organic', 514.29);
insert into produto (descricao, preco_unitario) values ('Star Fruit', 795.87);
insert into produto (descricao, preco_unitario) values ('Dish Towel', 458.96);
insert into produto (descricao, preco_unitario) values ('Mushroom - Chantrelle, Fresh', 519.25);
insert into produto (descricao, preco_unitario) values ('Salmon - Sockeye Raw', 257.96);
insert into produto (descricao, preco_unitario) values ('Cheese - Marble', 131.44);
insert into produto (descricao, preco_unitario) values ('Milk Powder', 301.68);
insert into produto (descricao, preco_unitario) values ('Carbonated Water - Orange', 494.96);
insert into produto (descricao, preco_unitario) values ('Ice Cream - Super Sandwich', 327.28);
insert into produto (descricao, preco_unitario) values ('Skirt - 24 Foot', 67.09);
insert into produto (descricao, preco_unitario) values ('Food Colouring - Pink', 370.55);
insert into produto (descricao, preco_unitario) values ('Bagelers - Cinn / Brown Sugar', 704.33);
insert into produto (descricao, preco_unitario) values ('Cakes Assorted', 808.89);
insert into produto (descricao, preco_unitario) values ('Cookies - Fortune', 850.44);
insert into produto (descricao, preco_unitario) values ('Currants', 912.03);
insert into produto (descricao, preco_unitario) values ('Bread - Dark Rye, Loaf', 15.23);
insert into produto (descricao, preco_unitario) values ('Flour - Bread', 423.62);
insert into produto (descricao, preco_unitario) values ('Garbage Bags - Black', 519.46);
insert into produto (descricao, preco_unitario) values ('Pepper - Green, Chili', 815.39);
insert into produto (descricao, preco_unitario) values ('Pesto - Primerba, Paste', 955.59);
insert into produto (descricao, preco_unitario) values ('Monkfish Fresh - Skin Off', 350.5);
insert into produto (descricao, preco_unitario) values ('Salt - Seasoned', 555.53);
insert into produto (descricao, preco_unitario) values ('Wine - Cava Aria Estate Brut', 186.21);
insert into produto (descricao, preco_unitario) values ('Yoghurt Tubes', 509.76);
insert into produto (descricao, preco_unitario) values ('Napkin - Beverge, White 2 - Ply', 260.4);
insert into produto (descricao, preco_unitario) values ('Wine - Ruffino Chianti Classico', 813.2);
insert into produto (descricao, preco_unitario) values ('Bread Cranberry Foccacia', 867.49);
insert into produto (descricao, preco_unitario) values ('Tea - Grapefruit Green Tea', 870.8);
insert into produto (descricao, preco_unitario) values ('Longos - Chicken Curried', 231.5);
insert into produto (descricao, preco_unitario) values ('Sauce - Hoisin', 652.79);
insert into produto (descricao, preco_unitario) values ('Wine - Sake', 521.78);
insert into produto (descricao, preco_unitario) values ('Milkettes - 2%', 50.97);
insert into produto (descricao, preco_unitario) values ('Clams - Littleneck, Whole', 88.4);
insert into produto (descricao, preco_unitario) values ('Fuji Apples', 770.1);
insert into produto (descricao, preco_unitario) values ('Beer - Guiness', 523.11);
insert into produto (descricao, preco_unitario) values ('Trueblue - Blueberry 12x473ml', 659.88);
insert into produto (descricao, preco_unitario) values ('Bread - Ciabatta Buns', 578.6);
insert into produto (descricao, preco_unitario) values ('Wine - Magnotta - Belpaese', 870.52);
insert into produto (descricao, preco_unitario) values ('Compound - Orange', 663.31);
insert into produto (descricao, preco_unitario) values ('Crackers - Graham', 143.28);
insert into produto (descricao, preco_unitario) values ('Breakfast Quesadillas', 427.05);
insert into produto (descricao, preco_unitario) values ('Wine - Jafflin Bourgongone', 504.62);
insert into produto (descricao, preco_unitario) values ('Sprouts - Onion', 964.79);
insert into produto (descricao, preco_unitario) values ('Chinese Foods - Thick Noodles', 349.95);
insert into produto (descricao, preco_unitario) values ('Chocolate - Feathers', 948.74);
insert into produto (descricao, preco_unitario) values ('Flour - Rye', 627.76);
insert into produto (descricao, preco_unitario) values ('Berry Brulee', 190.85);
insert into produto (descricao, preco_unitario) values ('Pepsi - Diet, 355 Ml', 66.48);
insert into produto (descricao, preco_unitario) values ('Bar - Sweet And Salty Chocolate', 726.51);
insert into produto (descricao, preco_unitario) values ('Wine - Magnotta - Pinot Gris Sr', 285.85);
insert into produto (descricao, preco_unitario) values ('Cheese Cloth', 621.12);
insert into produto (descricao, preco_unitario) values ('Pastry - Apple Large', 506.19);
insert into produto (descricao, preco_unitario) values ('Bread - Multigrain Oval', 49.21);
insert into produto (descricao, preco_unitario) values ('Longos - Lasagna Veg', 224.23);
insert into produto (descricao, preco_unitario) values ('Pastry - Cherry Danish - Mini', 727.45);
insert into produto (descricao, preco_unitario) values ('Pork - Back, Long Cut, Boneless', 380.44);
insert into produto (descricao, preco_unitario) values ('Lemonade - Mandarin, 591 Ml', 932.89);
insert into produto (descricao, preco_unitario) values ('Bamboo Shoots - Sliced', 442.19);
insert into produto (descricao, preco_unitario) values ('Beef - Flank Steak', 451.26);
insert into produto (descricao, preco_unitario) values ('Wine - Fume Blanc Fetzer', 713.28);
insert into produto (descricao, preco_unitario) values ('Napkin - Cocktail,beige 2 - Ply', 658.15);
insert into produto (descricao, preco_unitario) values ('Bread - French Baquette', 392.8);
insert into produto (descricao, preco_unitario) values ('Bread - 10 Grain', 211.1);
insert into produto (descricao, preco_unitario) values ('Potatoes - Yukon Gold, 80 Ct', 920.01);
insert into produto (descricao, preco_unitario) values ('Pastry - Trippleberry Muffin - Mini', 529.29);
insert into produto (descricao, preco_unitario) values ('Salt - Kosher', 382.48);
insert into produto (descricao, preco_unitario) values ('Tart Shells - Sweet, 3', 638.0);
insert into produto (descricao, preco_unitario) values ('Beef - Ox Tail, Frozen', 670.19);
insert into produto (descricao, preco_unitario) values ('Bread - Hot Dog Buns', 973.74);
insert into produto (descricao, preco_unitario) values ('Bread - Rosemary Focaccia', 391.41);
insert into produto (descricao, preco_unitario) values ('Juice - Apple, 341 Ml', 237.09);
insert into produto (descricao, preco_unitario) values ('Cod - Fillets', 632.07);
insert into produto (descricao, preco_unitario) values ('Wine - White, Chardonnay', 94.48);
insert into produto (descricao, preco_unitario) values ('White Fish - Filets', 269.35);
insert into produto (descricao, preco_unitario) values ('Slt - Individual Portions', 810.12);
insert into produto (descricao, preco_unitario) values ('Muffin - Zero Transfat', 900.31);
insert into produto (descricao, preco_unitario) values ('Cheese - Le Cheve Noir', 882.78);
insert into produto (descricao, preco_unitario) values ('Snapple Raspberry Tea', 590.28);
insert into produto (descricao, preco_unitario) values ('Eggplant - Regular', 241.45);
insert into produto (descricao, preco_unitario) values ('Beef - Bresaola', 174.52);
insert into produto (descricao, preco_unitario) values ('Beans - Kidney, Canned', 120.37);
insert into produto (descricao, preco_unitario) values ('Sugar - Crumb', 257.27);
insert into produto (descricao, preco_unitario) values ('Salt - Sea', 550.38);
insert into produto (descricao, preco_unitario) values ('Wine - Red, Black Opal Shiraz', 548.73);
insert into produto (descricao, preco_unitario) values ('Wine - Sherry Dry Sack, William', 871.67);
insert into produto (descricao, preco_unitario) values ('Oil - Food, Lacquer Spray', 242.24);
insert into produto (descricao, preco_unitario) values ('Extract - Rum', 200.59);
insert into produto (descricao, preco_unitario) values ('Yogurt - Banana, 175 Gr', 667.56);
insert into produto (descricao, preco_unitario) values ('Milk Powder', 750.03);
insert into produto (descricao, preco_unitario) values ('Cardamon Ground', 722.29);
insert into produto (descricao, preco_unitario) values ('Cookie Dough - Oatmeal Rasin', 844.92);
insert into produto (descricao, preco_unitario) values ('Muskox - French Rack', 348.17);
insert into produto (descricao, preco_unitario) values ('Rum - Mount Gay Eclipes', 518.13);
insert into produto (descricao, preco_unitario) values ('Liners - Baking Cups', 822.05);
insert into produto (descricao, preco_unitario) values ('Cookie Trail Mix', 287.7);
insert into produto (descricao, preco_unitario) values ('Carbonated Water - Blackcherry', 137.9);
insert into produto (descricao, preco_unitario) values ('Cherries - Frozen', 994.4);
insert into produto (descricao, preco_unitario) values ('Appetizer - Shrimp Puff', 447.6);
insert into produto (descricao, preco_unitario) values ('Mix - Cocktail Strawberry Daiquiri', 927.59);
insert into produto (descricao, preco_unitario) values ('Durian Fruit', 382.36);
insert into produto (descricao, preco_unitario) values ('Kellogs Special K Cereal', 609.71);
insert into produto (descricao, preco_unitario) values ('Table Cloth 54x54 White', 937.99);
insert into produto (descricao, preco_unitario) values ('Wine - Dubouef Macon - Villages', 661.7);
insert into produto (descricao, preco_unitario) values ('Broom - Angled', 673.03);
insert into produto (descricao, preco_unitario) values ('Clams - Littleneck, Whole', 67.36);
insert into produto (descricao, preco_unitario) values ('Chips - Assorted', 8.48);
insert into produto (descricao, preco_unitario) values ('Cumin - Ground', 319.33);
insert into produto (descricao, preco_unitario) values ('Mace', 339.7);
insert into produto (descricao, preco_unitario) values ('Cheese - Cheddar With Claret', 875.61);
insert into produto (descricao, preco_unitario) values ('Pepper - Chilli Seeds Mild', 866.49);
insert into produto (descricao, preco_unitario) values ('Ham - Virginia', 785.3);
insert into produto (descricao, preco_unitario) values ('Vinegar - Rice', 418.89);
insert into produto (descricao, preco_unitario) values ('Juice - Lagoon Mango', 218.46);
insert into produto (descricao, preco_unitario) values ('Sausage - Chorizo', 511.02);
insert into produto (descricao, preco_unitario) values ('Nut - Pumpkin Seeds', 859.31);
insert into produto (descricao, preco_unitario) values ('Cucumber - Pickling Ontario', 413.18);
insert into produto (descricao, preco_unitario) values ('Chicken - Base', 562.62);
insert into produto (descricao, preco_unitario) values ('Hickory Smoke, Liquid', 226.7);
insert into produto (descricao, preco_unitario) values ('Rosemary - Fresh', 767.21);
insert into produto (descricao, preco_unitario) values ('Ham - Procutinni', 185.09);
insert into produto (descricao, preco_unitario) values ('Pork - Ground', 296.3);
insert into produto (descricao, preco_unitario) values ('Cup - Translucent 7 Oz Clear', 559.73);
insert into produto (descricao, preco_unitario) values ('Cheese - Brie, Triple Creme', 653.04);
insert into produto (descricao, preco_unitario) values ('Beef - Chuck, Boneless', 66.93);
insert into produto (descricao, preco_unitario) values ('Bagel - Whole White Sesame', 805.16);
insert into produto (descricao, preco_unitario) values ('Doilies - 8, Paper', 323.25);
insert into produto (descricao, preco_unitario) values ('Tea - Green', 342.65);
insert into produto (descricao, preco_unitario) values ('Squid - Tubes / Tenticles 10/20', 563.18);
insert into produto (descricao, preco_unitario) values ('Sauce - Caesar Dressing', 32.69);
insert into produto (descricao, preco_unitario) values ('Ham - Cooked Bayonne Tinned', 12.14);
insert into produto (descricao, preco_unitario) values ('Water - Mineral, Carbonated', 538.52);
insert into produto (descricao, preco_unitario) values ('Chocolate - Compound Coating', 962.44);
insert into produto (descricao, preco_unitario) values ('Flour - Strong', 498.44);
insert into produto (descricao, preco_unitario) values ('Cheese - Brie', 495.36);
insert into produto (descricao, preco_unitario) values ('Coffee Beans - Chocolate', 827.58);
insert into produto (descricao, preco_unitario) values ('Salmon - Whole, 4 - 6 Pounds', 434.56);
insert into produto (descricao, preco_unitario) values ('Wine - Alicanca Vinho Verde', 672.65);
insert into produto (descricao, preco_unitario) values ('Mountain Dew', 969.0);
insert into produto (descricao, preco_unitario) values ('Grapes - Black', 198.57);
insert into produto (descricao, preco_unitario) values ('Bread Ww Cluster', 250.76);
insert into produto (descricao, preco_unitario) values ('Wine - Magnotta - Pinot Gris Sr', 341.36);
insert into produto (descricao, preco_unitario) values ('Sardines', 522.33);
insert into produto (descricao, preco_unitario) values ('Frangelico', 158.93);
insert into produto (descricao, preco_unitario) values ('Tea Leaves - Oolong', 60.97);
insert into produto (descricao, preco_unitario) values ('Wine - Acient Coast Caberne', 363.68);
insert into produto (descricao, preco_unitario) values ('Wine - Two Oceans Cabernet', 667.71);
insert into produto (descricao, preco_unitario) values ('V8 Pet', 865.11);
insert into produto (descricao, preco_unitario) values ('Juice - Tomato, 10 Oz', 529.61);
insert into produto (descricao, preco_unitario) values ('Jam - Apricot', 515.59);
insert into produto (descricao, preco_unitario) values ('Pork - Hock And Feet Attached', 691.63);
insert into produto (descricao, preco_unitario) values ('Croissant, Raw - Mini', 934.45);
insert into produto (descricao, preco_unitario) values ('Phyllo Dough', 276.14);
insert into produto (descricao, preco_unitario) values ('Smoked Tongue', 682.54);
insert into produto (descricao, preco_unitario) values ('True - Vue Containers', 922.82);
insert into produto (descricao, preco_unitario) values ('Shrimp - 150 - 250', 772.36);
insert into produto (descricao, preco_unitario) values ('Wine - Sawmill Creek Autumn', 740.88);
insert into produto (descricao, preco_unitario) values ('Plastic Wrap', 296.61);
insert into produto (descricao, preco_unitario) values ('Placemat - Scallop, White', 695.85);
insert into produto (descricao, preco_unitario) values ('Butter - Salted', 234.24);
insert into produto (descricao, preco_unitario) values ('Containter - 3oz Microwave Rect.', 451.6);
insert into produto (descricao, preco_unitario) values ('Cheese - St. Andre', 702.88);
insert into produto (descricao, preco_unitario) values ('Kirsch - Schloss', 472.3);
insert into produto (descricao, preco_unitario) values ('Fiddlehead - Frozen', 542.98);
insert into produto (descricao, preco_unitario) values ('Table Cloth 53x53 White', 255.99);
insert into produto (descricao, preco_unitario) values ('Soup - Knorr, Country Bean', 470.98);
insert into produto (descricao, preco_unitario) values ('Table Cloth 62x114 White', 259.4);
insert into produto (descricao, preco_unitario) values ('Bread - Raisin', 335.6);
insert into produto (descricao, preco_unitario) values ('Yoghurt Tubes', 567.12);
insert into produto (descricao, preco_unitario) values ('Pepsi - Diet, 355 Ml', 856.7);
insert into produto (descricao, preco_unitario) values ('Sauce - Cranberry', 338.99);
insert into produto (descricao, preco_unitario) values ('Muffin Batt - Choc Chk', 59.64);
insert into produto (descricao, preco_unitario) values ('Pork - Caul Fat', 277.74);
insert into produto (descricao, preco_unitario) values ('Oil - Shortening,liqud, Fry', 303.81);
insert into produto (descricao, preco_unitario) values ('Lettuce - California Mix', 829.74);
insert into produto (descricao, preco_unitario) values ('Marzipan 50/50', 746.93);
insert into produto (descricao, preco_unitario) values ('Yams', 871.77);
insert into produto (descricao, preco_unitario) values ('Ecolab - Balanced Fusion', 328.25);
insert into produto (descricao, preco_unitario) values ('Jam - Strawberry, 20 Ml Jar', 195.41);
insert into produto (descricao, preco_unitario) values ('Icecream Bar - Del Monte', 614.89);
insert into produto (descricao, preco_unitario) values ('Crab - Claws, Snow 16 - 24', 972.57);
insert into produto (descricao, preco_unitario) values ('Wine - Maipo Valle Cabernet', 668.56);
insert into produto (descricao, preco_unitario) values ('Muffin - Zero Transfat', 793.81);
insert into produto (descricao, preco_unitario) values ('Cookie - Oreo 100x2', 891.42);
insert into produto (descricao, preco_unitario) values ('Sauce - Demi Glace', 143.04);
insert into produto (descricao, preco_unitario) values ('Yogurt - Blueberry, 175 Gr', 694.54);
insert into produto (descricao, preco_unitario) values ('Breakfast Quesadillas', 637.47);
insert into produto (descricao, preco_unitario) values ('Wine - Masi Valpolocell', 963.95);
insert into produto (descricao, preco_unitario) values ('Sprouts - Baby Pea Tendrils', 102.3);
insert into produto (descricao, preco_unitario) values ('Turkey - Breast, Smoked', 599.46);
insert into produto (descricao, preco_unitario) values ('Wine - Duboeuf Beaujolais', 657.32);
insert into produto (descricao, preco_unitario) values ('Broom - Angled', 441.92);
insert into produto (descricao, preco_unitario) values ('Chevril', 115.65);
insert into produto (descricao, preco_unitario) values ('Lotus Rootlets - Canned', 102.96);
insert into produto (descricao, preco_unitario) values ('Vinegar - White Wine', 880.39);
insert into produto (descricao, preco_unitario) values ('Gatorade - Fruit Punch', 432.09);
insert into produto (descricao, preco_unitario) values ('Table Cloth - 53x69 Colour', 996.62);
insert into produto (descricao, preco_unitario) values ('Onion - Dried', 986.97);
insert into produto (descricao, preco_unitario) values ('Carrots - Mini Red Organic', 626.64);
insert into produto (descricao, preco_unitario) values ('Pasta - Ravioli', 123.19);
insert into produto (descricao, preco_unitario) values ('Basil - Primerba, Paste', 319.26);
insert into produto (descricao, preco_unitario) values ('Bag - Regular Kraft 20 Lb', 744.61);
insert into produto (descricao, preco_unitario) values ('Smoked Tongue', 251.41);
insert into produto (descricao, preco_unitario) values ('Eggplant - Baby', 632.67);
insert into produto (descricao, preco_unitario) values ('Oxtail - Cut', 561.7);
insert into produto (descricao, preco_unitario) values ('Trout - Hot Smkd, Dbl Fillet', 862.94);
insert into produto (descricao, preco_unitario) values ('Tea - Earl Grey', 685.01);
insert into produto (descricao, preco_unitario) values ('Potatoes - Mini Red', 453.94);
insert into produto (descricao, preco_unitario) values ('Banana Turning', 117.7);
insert into produto (descricao, preco_unitario) values ('Pork - Bones', 732.43);
insert into produto (descricao, preco_unitario) values ('Energy Drink Red Bull', 778.19);
insert into produto (descricao, preco_unitario) values ('Onions - Dried, Chopped', 181.81);
insert into produto (descricao, preco_unitario) values ('French Pastries', 815.75);
insert into produto (descricao, preco_unitario) values ('Tea - Lemon Scented', 780.03);
insert into produto (descricao, preco_unitario) values ('Nut - Pecan, Halves', 646.85);
insert into produto (descricao, preco_unitario) values ('Cheese - Brie Roitelet', 371.04);
insert into produto (descricao, preco_unitario) values ('Flour - Buckwheat, Dark', 810.48);
insert into produto (descricao, preco_unitario) values ('Bread Base - Italian', 77.72);
insert into produto (descricao, preco_unitario) values ('Galliano', 67.31);
insert into produto (descricao, preco_unitario) values ('Beef Tenderloin Aaa', 192.87);
insert into produto (descricao, preco_unitario) values ('Cucumber - Pickling Ontario', 792.68);
insert into produto (descricao, preco_unitario) values ('Cheese - Mozzarella, Shredded', 149.96);
insert into produto (descricao, preco_unitario) values ('Wine - George Duboeuf Rose', 71.33);
insert into produto (descricao, preco_unitario) values ('Salami - Genova', 685.13);
insert into produto (descricao, preco_unitario) values ('Chocolate - White', 627.93);
insert into produto (descricao, preco_unitario) values ('Tomatoes - Diced, Canned', 282.6);
insert into produto (descricao, preco_unitario) values ('Celery', 252.69);
insert into produto (descricao, preco_unitario) values ('Pasta - Penne, Lisce, Dry', 568.62);
insert into produto (descricao, preco_unitario) values ('Scallops - 20/30', 296.59);
insert into produto (descricao, preco_unitario) values ('Plate Foam Laminated 9in Blk', 771.94);
insert into produto (descricao, preco_unitario) values ('Spice - Paprika', 521.26);
insert into produto (descricao, preco_unitario) values ('Chocolate - Mi - Amere Semi', 921.27);
insert into produto (descricao, preco_unitario) values ('Octopus - Baby, Cleaned', 160.92);
insert into produto (descricao, preco_unitario) values ('Beans - Fine', 702.28);
insert into produto (descricao, preco_unitario) values ('Soup - Campbells Broccoli', 19.86);
insert into produto (descricao, preco_unitario) values ('Crackers - Water', 174.03);
insert into produto (descricao, preco_unitario) values ('Nut - Pumpkin Seeds', 353.89);
insert into produto (descricao, preco_unitario) values ('Ham Black Forest', 445.98);
insert into produto (descricao, preco_unitario) values ('Scallops - 10/20', 532.3);
insert into produto (descricao, preco_unitario) values ('Burger Veggie', 728.26);
insert into produto (descricao, preco_unitario) values ('Pumpkin - Seed', 43.38);
insert into produto (descricao, preco_unitario) values ('Sausage - Blood Pudding', 783.52);
insert into produto (descricao, preco_unitario) values ('Gatorade - Fruit Punch', 805.26);
insert into produto (descricao, preco_unitario) values ('Buttons', 520.92);
insert into produto (descricao, preco_unitario) values ('Puree - Mango', 52.34);
insert into produto (descricao, preco_unitario) values ('Wine - Jaboulet Cotes Du Rhone', 507.82);
insert into produto (descricao, preco_unitario) values ('Chocolate - White', 883.7);
insert into produto (descricao, preco_unitario) values ('Avocado', 576.62);
insert into produto (descricao, preco_unitario) values ('Isomalt', 747.96);
insert into produto (descricao, preco_unitario) values ('Sausage - Andouille', 305.14);
insert into produto (descricao, preco_unitario) values ('Potatoes - Yukon Gold 5 Oz', 237.73);
insert into produto (descricao, preco_unitario) values ('Pails With Lids', 999.85);
insert into produto (descricao, preco_unitario) values ('Sausage - Blood Pudding', 706.86);
insert into produto (descricao, preco_unitario) values ('Chicken - Soup Base', 956.69);
insert into produto (descricao, preco_unitario) values ('Caviar - Salmon', 480.83);
insert into produto (descricao, preco_unitario) values ('Filo Dough', 159.55);
insert into produto (descricao, preco_unitario) values ('Cheese - Cream Cheese', 172.71);
insert into produto (descricao, preco_unitario) values ('Beef - Sushi Flat Iron Steak', 8.9);
insert into produto (descricao, preco_unitario) values ('Pasta - Penne, Lisce, Dry', 553.77);
insert into produto (descricao, preco_unitario) values ('Veal - Brisket, Provimi,bnls', 744.13);
insert into produto (descricao, preco_unitario) values ('Croissant, Raw - Mini', 329.78);
insert into produto (descricao, preco_unitario) values ('Bar Special K', 723.81);
insert into produto (descricao, preco_unitario) values ('Red Pepper Paste', 321.54);
insert into produto (descricao, preco_unitario) values ('Rice - Wild', 980.9);
insert into produto (descricao, preco_unitario) values ('Muffin Hinge 117n', 161.91);
insert into produto (descricao, preco_unitario) values ('Sauce - Chili', 706.45);
insert into produto (descricao, preco_unitario) values ('Oven Mitt - 13 Inch', 164.76);
insert into produto (descricao, preco_unitario) values ('Cup - 8oz Coffee Perforated', 421.48);
insert into produto (descricao, preco_unitario) values ('Sauce - Black Current, Dry Mix', 944.62);
insert into produto (descricao, preco_unitario) values ('Cheese - Boursin, Garlic / Herbs', 778.56);
insert into produto (descricao, preco_unitario) values ('Anchovy Paste - 56 G Tube', 184.0);
insert into produto (descricao, preco_unitario) values ('Tarragon - Fresh', 436.59);
insert into produto (descricao, preco_unitario) values ('Energy Drink - Franks Original', 998.1);
insert into produto (descricao, preco_unitario) values ('Sprite - 355 Ml', 208.38);
insert into produto (descricao, preco_unitario) values ('Nantucket - Pomegranate Pear', 635.94);
insert into produto (descricao, preco_unitario) values ('Cheese - Gorgonzola', 891.5);
insert into produto (descricao, preco_unitario) values ('Wine - Segura Viudas Aria Brut', 794.55);
insert into produto (descricao, preco_unitario) values ('Trout Rainbow Whole', 284.23);
insert into produto (descricao, preco_unitario) values ('Ezy Change Mophandle', 859.4);
insert into produto (descricao, preco_unitario) values ('Water - Spring Water, 355 Ml', 466.06);
insert into produto (descricao, preco_unitario) values ('Flour - So Mix Cake White', 87.84);
insert into produto (descricao, preco_unitario) values ('Sauce - Ranch Dressing', 460.4);
insert into produto (descricao, preco_unitario) values ('Squash - Pepper', 297.09);
insert into produto (descricao, preco_unitario) values ('Garlic', 494.11);
insert into produto (descricao, preco_unitario) values ('Beer - Blue Light', 377.7);
insert into produto (descricao, preco_unitario) values ('Steampan - Foil', 579.06);
insert into produto (descricao, preco_unitario) values ('Quail - Jumbo Boneless', 548.82);
insert into produto (descricao, preco_unitario) values ('Pop Shoppe Cream Soda', 996.69);
insert into produto (descricao, preco_unitario) values ('Butter Balls Salted', 471.25);
insert into produto (descricao, preco_unitario) values ('Dried Figs', 331.06);
insert into produto (descricao, preco_unitario) values ('Laundry - Bag Cloth', 111.01);
insert into produto (descricao, preco_unitario) values ('Radish', 689.42);
insert into produto (descricao, preco_unitario) values ('Shrimp - Prawn', 839.55);
insert into produto (descricao, preco_unitario) values ('Veal - Leg', 755.64);
insert into produto (descricao, preco_unitario) values ('Soup - Campbells, Butternut', 514.31);
insert into produto (descricao, preco_unitario) values ('Orange - Tangerine', 903.6);
insert into produto (descricao, preco_unitario) values ('Dip - Tapenade', 765.27);
insert into produto (descricao, preco_unitario) values ('Food Colouring - Blue', 827.74);
insert into produto (descricao, preco_unitario) values ('Crackers - Water', 580.69);
insert into produto (descricao, preco_unitario) values ('Pastry - Cherry Danish - Mini', 782.95);
insert into produto (descricao, preco_unitario) values ('Wine - Fume Blanc Fetzer', 643.6);
insert into produto (descricao, preco_unitario) values ('Nutmeg - Ground', 40.31);
insert into produto (descricao, preco_unitario) values ('Pork - Kidney', 949.75);
insert into produto (descricao, preco_unitario) values ('Ketchup - Tomato', 130.94);
insert into produto (descricao, preco_unitario) values ('Flower - Daisies', 612.09);
insert into produto (descricao, preco_unitario) values ('Yams', 526.11);
insert into produto (descricao, preco_unitario) values ('Artichoke - Hearts, Canned', 984.17);
insert into produto (descricao, preco_unitario) values ('Pear - Prickly', 569.44);
insert into produto (descricao, preco_unitario) values ('Wine - Touraine Azay - Le - Rideau', 479.97);
insert into produto (descricao, preco_unitario) values ('Paper - Brown Paper Mini Cups', 151.56);
insert into produto (descricao, preco_unitario) values ('Beef - Prime Rib Aaa', 885.59);
insert into produto (descricao, preco_unitario) values ('Juice - Ocean Spray Kiwi', 946.36);
insert into produto (descricao, preco_unitario) values ('Salt - Table', 392.86);
insert into produto (descricao, preco_unitario) values ('Spice - Montreal Steak Spice', 713.19);
insert into produto (descricao, preco_unitario) values ('Vinegar - Balsamic, White', 593.59);
insert into produto (descricao, preco_unitario) values ('Blueberries - Frozen', 833.49);
insert into produto (descricao, preco_unitario) values ('Smoked Paprika', 337.09);
insert into produto (descricao, preco_unitario) values ('Chicken - White Meat, No Tender', 198.54);
insert into produto (descricao, preco_unitario) values ('Cup - Translucent 7 Oz Clear', 712.77);
insert into produto (descricao, preco_unitario) values ('Sun - Dried Tomatoes', 369.06);
insert into produto (descricao, preco_unitario) values ('Coffee Decaf Colombian', 517.64);
insert into produto (descricao, preco_unitario) values ('Cheese - Swiss', 20.65);
insert into produto (descricao, preco_unitario) values ('Beer - Mill St Organic', 549.23);
insert into produto (descricao, preco_unitario) values ('Veal - Shank, Pieces', 488.53);
insert into produto (descricao, preco_unitario) values ('Glass - Juice Clear 5oz 55005', 908.5);
insert into produto (descricao, preco_unitario) values ('Wine - George Duboeuf Rose', 145.5);
insert into produto (descricao, preco_unitario) values ('Napkin - Beverage 1 Ply', 357.3);
insert into produto (descricao, preco_unitario) values ('Guinea Fowl', 540.04);
insert into produto (descricao, preco_unitario) values ('Emulsifier', 315.28);
insert into produto (descricao, preco_unitario) values ('Sugar - Icing', 158.16);
insert into produto (descricao, preco_unitario) values ('Food Colouring - Red', 889.25);
insert into produto (descricao, preco_unitario) values ('Cookies Oatmeal Raisin', 49.79);
insert into produto (descricao, preco_unitario) values ('Cake - Cake Sheet Macaroon', 876.53);
insert into produto (descricao, preco_unitario) values ('Flour - So Mix Cake White', 186.54);
insert into produto (descricao, preco_unitario) values ('Artichokes - Knobless, White', 14.38);
insert into produto (descricao, preco_unitario) values ('Jam - Raspberry', 910.5);
insert into produto (descricao, preco_unitario) values ('Ecolab - Mikroklene 4/4 L', 733.07);
insert into produto (descricao, preco_unitario) values ('Veal Inside - Provimi', 90.26);
insert into produto (descricao, preco_unitario) values ('Sauce - Rosee', 434.9);
insert into produto (descricao, preco_unitario) values ('Flour - All Purpose', 602.96);
insert into produto (descricao, preco_unitario) values ('Cocoa Butter', 303.67);
insert into produto (descricao, preco_unitario) values ('Soup - Campbells, Cream Of', 656.69);
insert into produto (descricao, preco_unitario) values ('Nut - Peanut, Roasted', 852.75);
insert into produto (descricao, preco_unitario) values ('Ginger - Fresh', 230.96);
insert into produto (descricao, preco_unitario) values ('Tomato - Green', 879.36);
insert into produto (descricao, preco_unitario) values ('Flour - Whole Wheat', 198.72);
insert into produto (descricao, preco_unitario) values ('Seedlings - Buckwheat, Organic', 949.85);
insert into produto (descricao, preco_unitario) values ('Wine - Sauvignon Blanc Oyster', 518.51);
insert into produto (descricao, preco_unitario) values ('Pork - Hock And Feet Attached', 550.18);
insert into produto (descricao, preco_unitario) values ('Wine - Domaine Boyar Royal', 501.98);
insert into produto (descricao, preco_unitario) values ('Plasticspoonblack', 479.42);
insert into produto (descricao, preco_unitario) values ('Wine - Coteaux Du Tricastin Ac', 298.04);
insert into produto (descricao, preco_unitario) values ('Pepper - Yellow Bell', 87.34);
insert into produto (descricao, preco_unitario) values ('Puree - Raspberry', 721.72);
insert into produto (descricao, preco_unitario) values ('Cheese Cheddar Processed', 401.17);
insert into produto (descricao, preco_unitario) values ('Bread - Frozen Basket Variety', 612.49);
insert into produto (descricao, preco_unitario) values ('Pepper - White, Ground', 805.2);
insert into produto (descricao, preco_unitario) values ('Icecream - Dstk Super Cone', 436.3);
insert into produto (descricao, preco_unitario) values ('Soup - Beef, Base Mix', 858.81);
insert into produto (descricao, preco_unitario) values ('Shrimp - Black Tiger 6 - 8', 369.34);
insert into produto (descricao, preco_unitario) values ('Magnotta Bel Paese Red', 977.73);
insert into produto (descricao, preco_unitario) values ('Bread - Frozen Basket Variety', 73.04);
insert into produto (descricao, preco_unitario) values ('Muffin Hinge 117n', 457.19);
insert into produto (descricao, preco_unitario) values ('Peas - Frozen', 331.16);
insert into produto (descricao, preco_unitario) values ('Cheese - Asiago', 456.92);
insert into produto (descricao, preco_unitario) values ('Cheese - Goat With Herbs', 794.44);
insert into produto (descricao, preco_unitario) values ('Kaffir Lime Leaves', 39.08);
insert into produto (descricao, preco_unitario) values ('Mackerel Whole Fresh', 939.5);
insert into produto (descricao, preco_unitario) values ('Yeast Dry - Fermipan', 724.34);
insert into produto (descricao, preco_unitario) values ('Wine - Ej Gallo Sierra Valley', 175.81);
insert into produto (descricao, preco_unitario) values ('Flour - Teff', 161.27);
insert into produto (descricao, preco_unitario) values ('White Fish - Filets', 684.61);
insert into produto (descricao, preco_unitario) values ('V8 Splash Strawberry Banana', 422.56);
insert into produto (descricao, preco_unitario) values ('Pastry - Apple Large', 653.3);
insert into produto (descricao, preco_unitario) values ('Sauce - Vodka Blush', 585.95);
insert into produto (descricao, preco_unitario) values ('Sausage - Blood Pudding', 805.31);
insert into produto (descricao, preco_unitario) values ('Bamboo Shoots - Sliced', 149.93);
insert into produto (descricao, preco_unitario) values ('Vinegar - Champagne', 804.0);
insert into produto (descricao, preco_unitario) values ('Beef Striploin Aaa', 66.89);
insert into produto (descricao, preco_unitario) values ('Wine - Alicanca Vinho Verde', 816.8);
insert into produto (descricao, preco_unitario) values ('Puree - Kiwi', 53.06);
insert into produto (descricao, preco_unitario) values ('Arizona - Plum Green Tea', 277.69);
insert into produto (descricao, preco_unitario) values ('Syrup - Monin, Irish Cream', 193.36);
insert into produto (descricao, preco_unitario) values ('Mushroom - Chanterelle, Dry', 194.39);
insert into produto (descricao, preco_unitario) values ('Bread - 10 Grain', 828.98);
insert into produto (descricao, preco_unitario) values ('Pasta - Lasagna Noodle, Frozen', 163.89);
insert into produto (descricao, preco_unitario) values ('Lamb - Shanks', 524.28);
insert into produto (descricao, preco_unitario) values ('Cheese - Valancey', 489.62);
insert into produto (descricao, preco_unitario) values ('Pepper - Sorrano', 236.81);
insert into produto (descricao, preco_unitario) values ('Sauce - Cranberry', 720.65);
insert into produto (descricao, preco_unitario) values ('Table Cloth 54x54 Colour', 165.14);
insert into produto (descricao, preco_unitario) values ('Water, Tap', 855.84);
insert into produto (descricao, preco_unitario) values ('Tequila - Sauza Silver', 66.05);
insert into produto (descricao, preco_unitario) values ('Oven Mitt - 13 Inch', 746.59);
insert into produto (descricao, preco_unitario) values ('Russian Prince', 962.2);
insert into produto (descricao, preco_unitario) values ('Muffin Mix - Banana Nut', 543.27);
insert into produto (descricao, preco_unitario) values ('Sole - Fillet', 119.58);
insert into produto (descricao, preco_unitario) values ('Nut - Walnut, Chopped', 514.38);
insert into produto (descricao, preco_unitario) values ('Pears - Anjou', 672.51);
insert into produto (descricao, preco_unitario) values ('Marjoram - Dried, Rubbed', 994.72);
insert into produto (descricao, preco_unitario) values ('Cod - Salted, Boneless', 198.41);
insert into produto (descricao, preco_unitario) values ('Cake - French Pear Tart', 312.22);
insert into produto (descricao, preco_unitario) values ('Oven Mitt - 13 Inch', 928.11);
insert into produto (descricao, preco_unitario) values ('Tuna - Sushi Grade', 256.42);
insert into produto (descricao, preco_unitario) values ('Wine - Baron De Rothschild', 633.47);
insert into produto (descricao, preco_unitario) values ('Quinoa', 98.92);
insert into produto (descricao, preco_unitario) values ('Wine - White, Concha Y Toro', 962.51);
insert into produto (descricao, preco_unitario) values ('Soup - Campbells', 458.98);
insert into produto (descricao, preco_unitario) values ('Wine - Magnotta - Pinot Gris Sr', 283.27);
insert into produto (descricao, preco_unitario) values ('Wine - Cotes Du Rhone Parallele', 911.18);
insert into produto (descricao, preco_unitario) values ('Coffee - Decafenated', 611.95);
insert into produto (descricao, preco_unitario) values ('Milk Powder', 835.44);
insert into produto (descricao, preco_unitario) values ('Shiratamako - Rice Flour', 972.1);
insert into produto (descricao, preco_unitario) values ('Wine - Magnotta - Red, Baco', 936.43);
insert into produto (descricao, preco_unitario) values ('Longos - Chicken Wings', 261.54);
insert into produto (descricao, preco_unitario) values ('Shrimp - 16 - 20 Cooked, Peeled', 905.3);
insert into produto (descricao, preco_unitario) values ('Mushroom - Trumpet, Dry', 224.05);
insert into produto (descricao, preco_unitario) values ('Lobster - Base', 171.1);
insert into produto (descricao, preco_unitario) values ('Wine - Crozes Hermitage E.', 812.66);
insert into produto (descricao, preco_unitario) values ('Beef - Cow Feet Split', 313.56);
insert into produto (descricao, preco_unitario) values ('Flower - Dish Garden', 765.71);
insert into produto (descricao, preco_unitario) values ('Sping Loaded Cup Dispenser', 23.38);
insert into produto (descricao, preco_unitario) values ('Wild Boar - Tenderloin', 143.03);
insert into produto (descricao, preco_unitario) values ('Pepper - Green', 988.47);
insert into produto (descricao, preco_unitario) values ('Tray - 12in Rnd Blk', 267.94);
insert into produto (descricao, preco_unitario) values ('Bread - Rolls, Rye', 775.99);
insert into produto (descricao, preco_unitario) values ('Table Cloth 144x90 White', 964.62);
insert into produto (descricao, preco_unitario) values ('Shichimi Togarashi Peppeers', 701.89);
insert into produto (descricao, preco_unitario) values ('Orange - Canned, Mandarin', 379.05);
insert into produto (descricao, preco_unitario) values ('Soup - Knorr, Country Bean', 153.0);
insert into produto (descricao, preco_unitario) values ('Stock - Veal, Brown', 538.53);
insert into produto (descricao, preco_unitario) values ('Pepper Squash', 372.98);
insert into produto (descricao, preco_unitario) values ('Wine - Magnotta - Red, Baco', 896.68);
insert into produto (descricao, preco_unitario) values ('Wine - Saint Emilion Calvet', 663.61);
insert into produto (descricao, preco_unitario) values ('Blueberries', 106.53);
insert into produto (descricao, preco_unitario) values ('Beer - Paulaner Hefeweisse', 548.54);
insert into produto (descricao, preco_unitario) values ('Sauce - Alfredo', 912.41);
insert into produto (descricao, preco_unitario) values ('Lamb - Sausage Casings', 60.88);
insert into produto (descricao, preco_unitario) values ('Island Oasis - Mango Daiquiri', 332.94);
insert into produto (descricao, preco_unitario) values ('Gingerale - Diet - Schweppes', 234.47);
insert into produto (descricao, preco_unitario) values ('Wine - Magnotta, White', 381.17);
insert into produto (descricao, preco_unitario) values ('Foil - Round Foil', 275.82);
insert into produto (descricao, preco_unitario) values ('Beef - Baby, Liver', 350.56);
insert into produto (descricao, preco_unitario) values ('Chinese Foods - Thick Noodles', 440.33);
insert into produto (descricao, preco_unitario) values ('Tomatoes - Grape', 999.85);
insert into produto (descricao, preco_unitario) values ('Wine - White, Schroder And Schyl', 522.14);
insert into produto (descricao, preco_unitario) values ('Kiwano', 653.53);
insert into produto (descricao, preco_unitario) values ('Tofu - Firm', 728.47);
insert into produto (descricao, preco_unitario) values ('Ice Cream Bar - Hageen Daz To', 83.14);
insert into produto (descricao, preco_unitario) values ('Chicken - Bones', 581.75);
insert into produto (descricao, preco_unitario) values ('Cheese - Woolwich Goat, Log', 900.54);
insert into produto (descricao, preco_unitario) values ('Beets - Pickled', 584.03);
insert into produto (descricao, preco_unitario) values ('Towels - Paper / Kraft', 20.56);
insert into produto (descricao, preco_unitario) values ('Country Roll', 647.53);
insert into produto (descricao, preco_unitario) values ('Tortillas - Flour, 8', 551.84);
insert into produto (descricao, preco_unitario) values ('Corn Meal', 448.9);
insert into produto (descricao, preco_unitario) values ('Ecolab Digiclean Mild Fm', 707.69);
insert into produto (descricao, preco_unitario) values ('Chivas Regal - 12 Year Old', 938.03);
insert into produto (descricao, preco_unitario) values ('Island Oasis - Peach Daiquiri', 238.95);
insert into produto (descricao, preco_unitario) values ('Grenadine', 171.6);
insert into produto (descricao, preco_unitario) values ('Asparagus - White, Canned', 493.96);
insert into produto (descricao, preco_unitario) values ('Wine - Red, Wolf Blass, Yellow', 115.71);
insert into produto (descricao, preco_unitario) values ('Bagel - Everything', 271.43);
insert into produto (descricao, preco_unitario) values ('Trout Rainbow Whole', 186.76);
insert into produto (descricao, preco_unitario) values ('Sachet', 643.71);
insert into produto (descricao, preco_unitario) values ('Chutney Sauce - Mango', 401.9);
insert into produto (descricao, preco_unitario) values ('Veal - Insides Provini', 365.14);
insert into produto (descricao, preco_unitario) values ('Table Cloth 54x54 Colour', 487.83);
insert into produto (descricao, preco_unitario) values ('Phyllo Dough', 422.34);
insert into produto (descricao, preco_unitario) values ('Cake - Pancake', 699.87);
insert into produto (descricao, preco_unitario) values ('Soup - Cream Of Broccoli', 512.61);
insert into produto (descricao, preco_unitario) values ('Butter Sweet', 52.23);
insert into produto (descricao, preco_unitario) values ('Pastry - Apple Large', 788.32);
insert into produto (descricao, preco_unitario) values ('Calypso - Strawberry Lemonade', 553.56);
insert into produto (descricao, preco_unitario) values ('Pastry - Cheese Baked Scones', 945.09);
insert into produto (descricao, preco_unitario) values ('Puree - Kiwi', 448.93);
insert into produto (descricao, preco_unitario) values ('Pears - Bosc', 159.75);
insert into produto (descricao, preco_unitario) values ('Cherries - Fresh', 54.39);
insert into produto (descricao, preco_unitario) values ('Daves Island Stinger', 351.47);
insert into produto (descricao, preco_unitario) values ('Syrup - Monin - Passion Fruit', 398.74);
insert into produto (descricao, preco_unitario) values ('Cheese - Roquefort Pappillon', 336.37);
insert into produto (descricao, preco_unitario) values ('Muffin - Carrot Individual Wrap', 478.66);
insert into produto (descricao, preco_unitario) values ('Calypso - Black Cherry Lemonade', 9.5);
insert into produto (descricao, preco_unitario) values ('Beef - Ox Tail, Frozen', 863.22);
insert into produto (descricao, preco_unitario) values ('Orange - Blood', 12.3);
insert into produto (descricao, preco_unitario) values ('Dome Lid Clear P92008h', 197.19);
insert into produto (descricao, preco_unitario) values ('Pepper - Chillies, Crushed', 901.57);
insert into produto (descricao, preco_unitario) values ('Extract - Vanilla,artificial', 746.63);
insert into produto (descricao, preco_unitario) values ('Evaporated Milk - Skim', 30.93);
insert into produto (descricao, preco_unitario) values ('Bagelers', 28.87);
insert into produto (descricao, preco_unitario) values ('Bread - Burger', 570.45);
insert into produto (descricao, preco_unitario) values ('Pasta - Fettuccine, Egg, Fresh', 950.64);
insert into produto (descricao, preco_unitario) values ('Salmon - Smoked, Sliced', 172.55);
insert into produto (descricao, preco_unitario) values ('Fish - Atlantic Salmon, Cold', 848.35);
insert into produto (descricao, preco_unitario) values ('Tuna - Canned, Flaked, Light', 688.39);
insert into produto (descricao, preco_unitario) values ('Bagelers - Cinn / Brown Sugar', 866.4);
insert into produto (descricao, preco_unitario) values ('Pasta - Orzo, Dry', 85.22);
insert into produto (descricao, preco_unitario) values ('Beer - Blue Light', 875.34);
insert into produto (descricao, preco_unitario) values ('Juice - Apple, 1.36l', 224.22);
insert into produto (descricao, preco_unitario) values ('Bread - Assorted Rolls', 591.45);
insert into produto (descricao, preco_unitario) values ('Pork - Hock And Feet Attached', 173.15);
insert into produto (descricao, preco_unitario) values ('Beer - Sleemans Cream Ale', 499.57);
insert into produto (descricao, preco_unitario) values ('Juice - Lime', 189.52);
insert into produto (descricao, preco_unitario) values ('Breakfast Quesadillas', 334.91);
insert into produto (descricao, preco_unitario) values ('Sausage - Blood Pudding', 94.05);
insert into produto (descricao, preco_unitario) values ('Pasta - Penne, Lisce, Dry', 895.67);
insert into produto (descricao, preco_unitario) values ('Sugar - White Packet', 105.69);
insert into produto (descricao, preco_unitario) values ('Truffle Shells - White Chocolate', 133.52);
insert into produto (descricao, preco_unitario) values ('Vinegar - Balsamic', 498.96);
insert into produto (descricao, preco_unitario) values ('Latex Rubber Gloves Size 9', 302.95);
insert into produto (descricao, preco_unitario) values ('Crab Meat Claw Pasteurise', 721.76);
insert into produto (descricao, preco_unitario) values ('Wasabi Powder', 943.61);
insert into produto (descricao, preco_unitario) values ('Wine - Chardonnay South', 646.51);
insert into produto (descricao, preco_unitario) values ('Sauerkraut', 444.2);
insert into produto (descricao, preco_unitario) values ('Cheese - Cheddarsliced', 830.58);
insert into produto (descricao, preco_unitario) values ('Bar - Granola Trail Mix Fruit Nut', 775.14);
insert into produto (descricao, preco_unitario) values ('Dragon Fruit', 98.99);
insert into produto (descricao, preco_unitario) values ('Crab - Back Fin Meat, Canned', 612.36);
insert into produto (descricao, preco_unitario) values ('Dish Towel', 688.92);
insert into produto (descricao, preco_unitario) values ('Jack Daniels', 508.37);
insert into produto (descricao, preco_unitario) values ('Oil - Truffle, Black', 605.12);
insert into produto (descricao, preco_unitario) values ('Madeira', 683.73);
insert into produto (descricao, preco_unitario) values ('Soup - Campbells, Cream Of', 937.55);
insert into produto (descricao, preco_unitario) values ('Grapes - Black', 323.57);
insert into produto (descricao, preco_unitario) values ('Pork - Smoked Kassler', 64.88);
insert into produto (descricao, preco_unitario) values ('Capon - Breast, Double, Wing On', 360.8);
insert into produto (descricao, preco_unitario) values ('Beans - Fava Fresh', 923.35);
insert into produto (descricao, preco_unitario) values ('Chicken Breast Wing On', 135.55);
insert into produto (descricao, preco_unitario) values ('Squid - U 5', 10.66);
insert into produto (descricao, preco_unitario) values ('Sardines', 56.85);
insert into produto (descricao, preco_unitario) values ('Pumpkin - Seed', 364.33);
insert into produto (descricao, preco_unitario) values ('Southern Comfort', 325.53);
insert into produto (descricao, preco_unitario) values ('Liqueur - Melon', 287.05);
insert into produto (descricao, preco_unitario) values ('Sage Derby', 599.31);
insert into produto (descricao, preco_unitario) values ('Doilies - 10, Paper', 805.89);
insert into produto (descricao, preco_unitario) values ('Pasta - Canelloni, Single Serve', 252.66);
insert into produto (descricao, preco_unitario) values ('Beer - True North Strong Ale', 124.29);
insert into produto (descricao, preco_unitario) values ('Seabream Whole Farmed', 957.75);
insert into produto (descricao, preco_unitario) values ('Wine - White, Riesling, Henry Of', 480.67);
insert into produto (descricao, preco_unitario) values ('Longos - Chicken Curried', 433.24);
insert into produto (descricao, preco_unitario) values ('Bowl 12 Oz - Showcase 92012', 681.39);
insert into produto (descricao, preco_unitario) values ('Bacardi Limon', 771.61);
insert into produto (descricao, preco_unitario) values ('Cranberry Foccacia', 487.09);
insert into produto (descricao, preco_unitario) values ('Cookies - Englishbay Oatmeal', 615.64);
insert into produto (descricao, preco_unitario) values ('Skirt - 24 Foot', 783.59);
insert into produto (descricao, preco_unitario) values ('Veal - Sweetbread', 38.21);
insert into produto (descricao, preco_unitario) values ('Wine - Champagne Brut Veuve', 28.23);
insert into produto (descricao, preco_unitario) values ('Soup - Campbellschix Stew', 560.73);
insert into produto (descricao, preco_unitario) values ('Container - Hngd Cll Blk 7x7x3', 343.01);
insert into produto (descricao, preco_unitario) values ('Wine - Mas Chicet Rose, Vintage', 124.09);
insert into produto (descricao, preco_unitario) values ('Sping Loaded Cup Dispenser', 74.43);
insert into produto (descricao, preco_unitario) values ('Soup - Campbells Beef Noodle', 813.16);
insert into produto (descricao, preco_unitario) values ('Sauce - Sesame Thai Dressing', 668.5);
insert into produto (descricao, preco_unitario) values ('Glass - Wine, Plastic, Clear 5 Oz', 666.06);
insert into produto (descricao, preco_unitario) values ('Wine - Muscadet Sur Lie', 714.47);
insert into produto (descricao, preco_unitario) values ('Melon - Honey Dew', 815.82);
insert into produto (descricao, preco_unitario) values ('Shrimp - Black Tiger 13/15', 325.77);
insert into produto (descricao, preco_unitario) values ('Cheese - Cream Cheese', 16.32);
insert into produto (descricao, preco_unitario) values ('Orange - Canned, Mandarin', 543.08);
insert into produto (descricao, preco_unitario) values ('Bread - White, Unsliced', 593.07);
insert into produto (descricao, preco_unitario) values ('Mushroom - Morels, Dry', 557.69);
insert into produto (descricao, preco_unitario) values ('Pie Filling - Apple', 769.98);
insert into produto (descricao, preco_unitario) values ('Nut - Pecan, Halves', 160.93);
insert into produto (descricao, preco_unitario) values ('Wine - Periguita Fonseca', 627.4);
insert into produto (descricao, preco_unitario) values ('Papadam', 164.47);
insert into produto (descricao, preco_unitario) values ('Miso Paste White', 744.06);
insert into produto (descricao, preco_unitario) values ('Food Colouring - Blue', 398.96);
insert into produto (descricao, preco_unitario) values ('Cheese - Havarti, Salsa', 802.23);
insert into produto (descricao, preco_unitario) values ('Food Colouring - Pink', 571.73);
insert into produto (descricao, preco_unitario) values ('Nectarines', 721.08);
insert into produto (descricao, preco_unitario) values ('Rosemary - Dry', 328.77);
insert into produto (descricao, preco_unitario) values ('Ice Cream - Chocolate', 395.42);
insert into produto (descricao, preco_unitario) values ('Pasta - Spaghetti, Dry', 749.57);
insert into produto (descricao, preco_unitario) values ('Milk - Condensed', 452.18);
insert into produto (descricao, preco_unitario) values ('Banana - Green', 208.54);
insert into produto (descricao, preco_unitario) values ('Crush - Grape, 355 Ml', 967.62);
insert into produto (descricao, preco_unitario) values ('Rice - Brown', 212.47);
insert into produto (descricao, preco_unitario) values ('Plastic Arrow Stir Stick', 287.8);
insert into produto (descricao, preco_unitario) values ('Cleaner - Pine Sol', 637.84);
insert into produto (descricao, preco_unitario) values ('Squid Ink', 904.52);
insert into produto (descricao, preco_unitario) values ('Bread - Hamburger Buns', 634.86);
insert into produto (descricao, preco_unitario) values ('Apple - Macintosh', 851.18);
insert into produto (descricao, preco_unitario) values ('Wine - Barossa Valley Estate', 878.13);
insert into produto (descricao, preco_unitario) values ('Parsley Italian - Fresh', 85.18);
insert into produto (descricao, preco_unitario) values ('Wine - Duboeuf Beaujolais', 586.25);
insert into produto (descricao, preco_unitario) values ('Lamb - Rack', 874.48);
insert into produto (descricao, preco_unitario) values ('Pastry - French Mini Assorted', 830.26);
insert into produto (descricao, preco_unitario) values ('Apple - Delicious, Golden', 465.56);
insert into produto (descricao, preco_unitario) values ('Beer - Heinekin', 473.42);
insert into produto (descricao, preco_unitario) values ('Drambuie', 939.99);
insert into produto (descricao, preco_unitario) values ('Chicken Breast Wing On', 296.28);
insert into produto (descricao, preco_unitario) values ('Fudge - Chocolate Fudge', 41.49);
insert into produto (descricao, preco_unitario) values ('Potatoes - Fingerling 4 Oz', 329.6);
insert into produto (descricao, preco_unitario) values ('Yokaline', 178.1);
insert into produto (descricao, preco_unitario) values ('Sultanas', 60.44);
insert into produto (descricao, preco_unitario) values ('Cheese Cloth No 60', 250.98);
insert into produto (descricao, preco_unitario) values ('Beer - Upper Canada Light', 385.65);
insert into produto (descricao, preco_unitario) values ('Couscous', 241.63);
insert into produto (descricao, preco_unitario) values ('Pecan Raisin - Tarts', 110.96);
insert into produto (descricao, preco_unitario) values ('Flower - Dish Garden', 69.6);
insert into produto (descricao, preco_unitario) values ('Milk - Chocolate 500ml', 826.11);
insert into produto (descricao, preco_unitario) values ('Syrup - Monin - Blue Curacao', 855.24);
insert into produto (descricao, preco_unitario) values ('Chevere Logs', 311.77);
insert into produto (descricao, preco_unitario) values ('Salt - Kosher', 552.53);
insert into produto (descricao, preco_unitario) values ('Chocolate - Pistoles, Lactee, Milk', 866.49);
insert into produto (descricao, preco_unitario) values ('Flour - Rye', 166.11);
insert into produto (descricao, preco_unitario) values ('Currants', 926.54);
insert into produto (descricao, preco_unitario) values ('Bonito Flakes - Toku Katsuo', 77.27);
insert into produto (descricao, preco_unitario) values ('Soup - Cream Of Broccoli, Dry', 12.16);
insert into produto (descricao, preco_unitario) values ('Mushroom - Oyster, Fresh', 193.51);
insert into produto (descricao, preco_unitario) values ('Kellogs Special K Cereal', 174.91);
insert into produto (descricao, preco_unitario) values ('Radish - Pickled', 817.1);
insert into produto (descricao, preco_unitario) values ('Bread - White Epi Baguette', 868.21);
insert into produto (descricao, preco_unitario) values ('Wooden Mop Handle', 707.17);
insert into produto (descricao, preco_unitario) values ('Jam - Marmalade, Orange', 605.31);
insert into produto (descricao, preco_unitario) values ('Chicken - Whole Fryers', 963.15);
insert into produto (descricao, preco_unitario) values ('Pail - 4l White, With Handle', 112.02);
insert into produto (descricao, preco_unitario) values ('Beef - Cow Feet Split', 436.05);
insert into produto (descricao, preco_unitario) values ('Amarula Cream', 14.58);
insert into produto (descricao, preco_unitario) values ('Sobe - Green Tea', 230.43);
insert into produto (descricao, preco_unitario) values ('Juice - Propel Sport', 275.37);
insert into produto (descricao, preco_unitario) values ('Rice Pilaf, Dry,package', 643.08);
insert into produto (descricao, preco_unitario) values ('Chicken - Ground', 269.54);
insert into produto (descricao, preco_unitario) values ('Pork - Sausage Casing', 495.01);
insert into produto (descricao, preco_unitario) values ('Oil - Shortening - All - Purpose', 531.61);
insert into produto (descricao, preco_unitario) values ('Table Cloth 90x90 White', 681.93);
insert into produto (descricao, preco_unitario) values ('Fish - Base, Bouillion', 91.25);
insert into produto (descricao, preco_unitario) values ('Coffee - Egg Nog Capuccino', 934.13);
insert into produto (descricao, preco_unitario) values ('Cheese - Bakers Cream Cheese', 568.19);
insert into produto (descricao, preco_unitario) values ('Pumpkin', 322.23);
insert into produto (descricao, preco_unitario) values ('Lid - High Heat, Super Clear', 816.42);
insert into produto (descricao, preco_unitario) values ('Bag Clear 10 Lb', 571.62);
insert into produto (descricao, preco_unitario) values ('Crush - Orange, 355ml', 878.1);
insert into produto (descricao, preco_unitario) values ('Cheese - Colby', 368.67);
insert into produto (descricao, preco_unitario) values ('Coffee - Hazelnut Cream', 186.3);
insert into produto (descricao, preco_unitario) values ('Shiro Miso', 741.53);
insert into produto (descricao, preco_unitario) values ('Baking Powder', 145.0);
insert into produto (descricao, preco_unitario) values ('Syrup - Monin, Irish Cream', 878.2);
insert into produto (descricao, preco_unitario) values ('French Pastry - Mini Chocolate', 936.38);
insert into produto (descricao, preco_unitario) values ('Beef - Tender Tips', 36.73);
insert into produto (descricao, preco_unitario) values ('Chocolate - Pistoles, Lactee, Milk', 986.31);
insert into produto (descricao, preco_unitario) values ('Beans - Turtle, Black, Dry', 993.54);
insert into produto (descricao, preco_unitario) values ('Wine - Chianti Classico Riserva', 971.23);
insert into produto (descricao, preco_unitario) values ('Island Oasis - Strawberry', 187.69);
insert into produto (descricao, preco_unitario) values ('Pear - Packum', 175.36);
insert into produto (descricao, preco_unitario) values ('Bread - Bistro Sour', 387.14);
insert into produto (descricao, preco_unitario) values ('Pork - Back, Long Cut, Boneless', 928.98);
insert into produto (descricao, preco_unitario) values ('Muffin - Banana Nut Individual', 484.87);
insert into produto (descricao, preco_unitario) values ('Sprite - 355 Ml', 870.53);
insert into produto (descricao, preco_unitario) values ('Table Cloth 81x81 White', 18.95);
insert into produto (descricao, preco_unitario) values ('Wine - Baron De Rothschild', 346.1);
insert into produto (descricao, preco_unitario) values ('The Pop Shoppe Pinapple', 415.06);
insert into produto (descricao, preco_unitario) values ('Venison - Ground', 344.01);
insert into produto (descricao, preco_unitario) values ('Container - Clear 32 Oz', 794.62);
insert into produto (descricao, preco_unitario) values ('Lettuce - Boston Bib', 200.74);
insert into produto (descricao, preco_unitario) values ('Wine - Chateauneuf Du Pape', 168.73);
insert into produto (descricao, preco_unitario) values ('Iced Tea - Lemon, 340ml', 998.9);
insert into produto (descricao, preco_unitario) values ('Pepper - Gypsy Pepper', 383.01);
insert into produto (descricao, preco_unitario) values ('Tea - Herbal - 6 Asst', 726.97);
insert into produto (descricao, preco_unitario) values ('Creme De Menthe Green', 273.3);
insert into produto (descricao, preco_unitario) values ('Chocolate Liqueur - Godet White', 517.17);
insert into produto (descricao, preco_unitario) values ('Tomatoes - Vine Ripe, Yellow', 890.48);
insert into produto (descricao, preco_unitario) values ('Cup - Translucent 7 Oz Clear', 436.9);
insert into produto (descricao, preco_unitario) values ('Cafe Royale', 610.01);
insert into produto (descricao, preco_unitario) values ('Chicken - Livers', 134.43);
insert into produto (descricao, preco_unitario) values ('Glaze - Apricot', 586.34);
insert into produto (descricao, preco_unitario) values ('Mushroom - Morels, Dry', 517.6);
insert into produto (descricao, preco_unitario) values ('Pasta - Cappellini, Dry', 815.33);
insert into produto (descricao, preco_unitario) values ('Cafe Royale', 513.08);
insert into produto (descricao, preco_unitario) values ('Venison - Racks Frenched', 324.81);
insert into produto (descricao, preco_unitario) values ('Pasta - Gnocchi, Potato', 762.52);
insert into produto (descricao, preco_unitario) values ('Chestnuts - Whole,canned', 371.27);
insert into produto (descricao, preco_unitario) values ('Canadian Emmenthal', 454.99);
insert into produto (descricao, preco_unitario) values ('Crab Meat Claw Pasteurise', 581.22);
insert into produto (descricao, preco_unitario) values ('Cake - Cake Sheet Macaroon', 288.18);
insert into produto (descricao, preco_unitario) values ('Pork - Bacon,back Peameal', 92.88);
insert into produto (descricao, preco_unitario) values ('Lamb - Shoulder, Boneless', 30.2);
insert into produto (descricao, preco_unitario) values ('Beef Striploin Aaa', 611.88);
insert into produto (descricao, preco_unitario) values ('Squash - Pattypan, Yellow', 896.46);
insert into produto (descricao, preco_unitario) values ('Turnip - White, Organic', 91.72);
insert into produto (descricao, preco_unitario) values ('Wine - Maipo Valle Cabernet', 601.58);
insert into produto (descricao, preco_unitario) values ('Bag - Bread, White, Plain', 299.75);
insert into produto (descricao, preco_unitario) values ('Numi - Assorted Teas', 112.22);
insert into produto (descricao, preco_unitario) values ('Chickhen - Chicken Phyllo', 652.9);
insert into produto (descricao, preco_unitario) values ('Sunflower Seed Raw', 632.23);
insert into produto (descricao, preco_unitario) values ('Wine - Zinfandel California 2002', 446.22);
insert into produto (descricao, preco_unitario) values ('Nantucket - 518ml', 234.49);
insert into produto (descricao, preco_unitario) values ('Bok Choy - Baby', 867.27);
insert into produto (descricao, preco_unitario) values ('Table Cloth 144x90 White', 606.79);
insert into produto (descricao, preco_unitario) values ('Macaroons - Homestyle Two Bit', 124.69);
insert into produto (descricao, preco_unitario) values ('Wine - Magnotta, White', 981.79);
insert into produto (descricao, preco_unitario) values ('Schnappes - Peach, Walkers', 850.77);
insert into produto (descricao, preco_unitario) values ('Yoplait Drink', 346.61);
insert into produto (descricao, preco_unitario) values ('Plate - Foam, Bread And Butter', 564.2);
insert into produto (descricao, preco_unitario) values ('Juice Peach Nectar', 936.45);
insert into produto (descricao, preco_unitario) values ('Beer - Mill St Organic', 490.44);
insert into produto (descricao, preco_unitario) values ('Lid Tray - 12in Dome', 897.5);
insert into produto (descricao, preco_unitario) values ('Iced Tea - Lemon, 340ml', 821.77);
insert into produto (descricao, preco_unitario) values ('Bread - Rolls, Corn', 294.58);
insert into produto (descricao, preco_unitario) values ('Apple - Delicious, Red', 595.46);
insert into produto (descricao, preco_unitario) values ('Carroway Seed', 49.07);
insert into produto (descricao, preco_unitario) values ('Durian Fruit', 748.7);
insert into produto (descricao, preco_unitario) values ('Curry Paste - Madras', 10.8);
insert into produto (descricao, preco_unitario) values ('Ginger - Ground', 564.25);
insert into produto (descricao, preco_unitario) values ('Ketchup - Tomato', 365.92);
insert into produto (descricao, preco_unitario) values ('Island Oasis - Pina Colada', 512.92);
insert into produto (descricao, preco_unitario) values ('Towels - Paper / Kraft', 171.23);
insert into produto (descricao, preco_unitario) values ('Trout - Hot Smkd, Dbl Fillet', 356.99);
insert into produto (descricao, preco_unitario) values ('Ecolab - Hand Soap Form Antibac', 803.57);
insert into produto (descricao, preco_unitario) values ('Sausage - Chorizo', 121.24);
insert into produto (descricao, preco_unitario) values ('Wine - Fume Blanc Fetzer', 311.9);
insert into produto (descricao, preco_unitario) values ('Melon - Honey Dew', 267.42);
insert into produto (descricao, preco_unitario) values ('Kiwi', 658.64);
insert into produto (descricao, preco_unitario) values ('Paper Towel Touchless', 68.32);
insert into produto (descricao, preco_unitario) values ('Wine - Cousino Macul Antiguas', 514.37);
insert into produto (descricao, preco_unitario) values ('Mince Meat - Filling', 317.2);
insert into produto (descricao, preco_unitario) values ('Lettuce - Escarole', 701.48);
insert into produto (descricao, preco_unitario) values ('Yoplait Drink', 996.83);
insert into produto (descricao, preco_unitario) values ('Gingerale - Diet - Schweppes', 808.41);
insert into produto (descricao, preco_unitario) values ('Sauce - White, Mix', 799.48);
insert into produto (descricao, preco_unitario) values ('Beef Striploin Aaa', 908.73);
insert into produto (descricao, preco_unitario) values ('Salt - Celery', 930.08);
insert into produto (descricao, preco_unitario) values ('Soup Campbells - Tomato Bisque', 524.77);
insert into produto (descricao, preco_unitario) values ('Ecolab - Lime - A - Way 4/4 L', 648.83);
insert into produto (descricao, preco_unitario) values ('Magnotta Bel Paese Red', 243.05);
insert into produto (descricao, preco_unitario) values ('Higashimaru Usukuchi Soy', 277.05);
insert into produto (descricao, preco_unitario) values ('Lamb Rack - Ontario', 205.78);
insert into produto (descricao, preco_unitario) values ('Plate Foam Laminated 9in Blk', 585.02);
insert into produto (descricao, preco_unitario) values ('Longos - Chicken Cordon Bleu', 34.74);
insert into produto (descricao, preco_unitario) values ('Pastry - Apple Large', 816.31);
insert into produto (descricao, preco_unitario) values ('Skirt - 24 Foot', 743.3);
insert into produto (descricao, preco_unitario) values ('Limes', 137.55);
insert into produto (descricao, preco_unitario) values ('Mint - Fresh', 208.22);
insert into produto (descricao, preco_unitario) values ('Lumpfish Black', 203.53);
insert into produto (descricao, preco_unitario) values ('Kaffir Lime Leaves', 688.97);
insert into produto (descricao, preco_unitario) values ('Rum - Dark, Bacardi, Black', 644.66);
insert into produto (descricao, preco_unitario) values ('Wine - Vidal Icewine Magnotta', 16.91);
insert into produto (descricao, preco_unitario) values ('Wine - Chardonnay Mondavi', 17.85);
insert into produto (descricao, preco_unitario) values ('Triple Sec - Mcguinness', 509.7);
insert into produto (descricao, preco_unitario) values ('Bread - Hot Dog Buns', 798.22);
insert into produto (descricao, preco_unitario) values ('Truffle Shells - White Chocolate', 881.9);
insert into produto (descricao, preco_unitario) values ('Rum - Mount Gay Eclipes', 513.26);
insert into produto (descricao, preco_unitario) values ('Salmon - Fillets', 520.75);
insert into produto (descricao, preco_unitario) values ('Passion Fruit', 750.82);
insert into produto (descricao, preco_unitario) values ('Lobster - Baby, Boiled', 157.66);
insert into produto (descricao, preco_unitario) values ('V8 - Vegetable Cocktail', 618.35);
insert into produto (descricao, preco_unitario) values ('Rolled Oats', 825.2);
insert into produto (descricao, preco_unitario) values ('Ice Cream - Life Savers', 11.23);
insert into produto (descricao, preco_unitario) values ('Coriander - Ground', 514.6);
insert into produto (descricao, preco_unitario) values ('Pepsi, 355 Ml', 940.02);
insert into produto (descricao, preco_unitario) values ('Turkey - Breast, Smoked', 191.51);
insert into produto (descricao, preco_unitario) values ('Corn - On The Cob', 142.16);
insert into produto (descricao, preco_unitario) values ('Veal - Slab Bacon', 750.34);
insert into produto (descricao, preco_unitario) values ('Creme De Menthe Green', 326.17);
insert into produto (descricao, preco_unitario) values ('Beer - Rickards Red', 110.24);
insert into produto (descricao, preco_unitario) values ('Wine - Rioja Campo Viejo', 167.6);
insert into produto (descricao, preco_unitario) values ('Cake - Dulce De Leche', 652.46);
insert into produto (descricao, preco_unitario) values ('Yeast Dry - Fermipan', 113.23);
insert into produto (descricao, preco_unitario) values ('Wine - Peller Estates Late', 422.52);
insert into produto (descricao, preco_unitario) values ('Lettuce - Lolla Rosa', 89.06);
insert into produto (descricao, preco_unitario) values ('Coffee Swiss Choc Almond', 492.16);
insert into produto (descricao, preco_unitario) values ('Flower - Commercial Spider', 5.39);
insert into produto (descricao, preco_unitario) values ('Butter Balls Salted', 147.93);
insert into produto (descricao, preco_unitario) values ('Liquid Aminios Acid - Braggs', 109.43);
insert into produto (descricao, preco_unitario) values ('Doilies - 10, Paper', 406.52);
insert into produto (descricao, preco_unitario) values ('Lettuce - Lambs Mash', 340.64);
insert into produto (descricao, preco_unitario) values ('Yogurt - Blueberry, 175 Gr', 721.49);
insert into produto (descricao, preco_unitario) values ('Ecolab Digiclean Mild Fm', 276.84);
insert into produto (descricao, preco_unitario) values ('Jam - Raspberry,jar', 209.67);
insert into produto (descricao, preco_unitario) values ('Calypso - Pineapple Passion', 20.96);
insert into produto (descricao, preco_unitario) values ('Truffle Paste', 784.24);
insert into produto (descricao, preco_unitario) values ('Tarragon - Fresh', 389.45);
insert into produto (descricao, preco_unitario) values ('Gherkin', 523.37);
insert into produto (descricao, preco_unitario) values ('Contreau', 961.59);
insert into produto (descricao, preco_unitario) values ('Pea - Snow', 796.08);
insert into produto (descricao, preco_unitario) values ('Lychee', 177.61);
insert into produto (descricao, preco_unitario) values ('Cheese - Victor Et Berthold', 379.22);
insert into produto (descricao, preco_unitario) values ('Pimento - Canned', 260.08);
insert into produto (descricao, preco_unitario) values ('Syrup - Golden, Lyles', 739.93);
insert into produto (descricao, preco_unitario) values ('Milk - Chocolate 250 Ml', 49.41);
insert into produto (descricao, preco_unitario) values ('Pork - Loin, Boneless', 354.69);
insert into produto (descricao, preco_unitario) values ('Pasta - Bauletti, Chicken White', 405.88);
insert into produto (descricao, preco_unitario) values ('Extract - Almond', 510.08);
insert into produto (descricao, preco_unitario) values ('Sauce - Hp', 398.34);
insert into produto (descricao, preco_unitario) values ('Lamb - Ground', 960.16);
insert into produto (descricao, preco_unitario) values ('Uniform Linen Charge', 34.29);
insert into produto (descricao, preco_unitario) values ('Syrup - Pancake', 391.86);
insert into produto (descricao, preco_unitario) values ('Beef - Top Sirloin - Aaa', 999.42);
insert into produto (descricao, preco_unitario) values ('Lettuce - Curly Endive', 321.81);
insert into produto (descricao, preco_unitario) values ('Fish - Halibut, Cold Smoked', 653.27);
insert into produto (descricao, preco_unitario) values ('Lumpfish Black', 802.39);
insert into produto (descricao, preco_unitario) values ('Pasta - Orzo, Dry', 481.27);
insert into produto (descricao, preco_unitario) values ('Chicken Thigh - Bone Out', 92.8);
insert into produto (descricao, preco_unitario) values ('Chicken Breast Wing On', 294.59);
insert into produto (descricao, preco_unitario) values ('Soup Campbells Split Pea And Ham', 493.27);
insert into produto (descricao, preco_unitario) values ('Beer - Creemore', 876.31);
insert into produto (descricao, preco_unitario) values ('Gatorade - Fruit Punch', 466.28);
insert into produto (descricao, preco_unitario) values ('Lamb - Whole, Frozen', 817.01);
insert into produto (descricao, preco_unitario) values ('Eggroll', 672.85);
insert into produto (descricao, preco_unitario) values ('Snapple Lemon Tea', 245.15);
insert into produto (descricao, preco_unitario) values ('Chicken - Leg, Boneless', 202.26);
insert into produto (descricao, preco_unitario) values ('Grapefruit - White', 912.75);
